apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
  - name: crccheck-hello-world
    image: crccheck/hello-world
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80

  - name: mwwhited-hello-world
    image: mwwhited/hello
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8001
