version: '1.0'
services:
  jupyter-lab:
    build: .
    ports:
      - "8888:8888"
    volumes:
       #- "C:/Repos/github/YearOfLanguages2023/src/tensorflow:/tensorflow"
       - "./:/tensorflow"
       - "./src/:/src"
       - "../../../../cache/keras/:/keras"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]              