version: '1.0'
services:
  jupyter-lab:
    build: .
    ports:
      - "8888:8888"
    volumes:
       #- "C:/Repos/github/YearOfLanguages2023/src/tensorflow:/tensorflow"
       - "./:/tensorflow"
       - "./src/:/src"
       - "../../../../cache/keras/:/keras"
    deploy:
      resources:
        reservations:
          devices:
           # this enable the GPU from docker
            - driver: nvidia
              count: 1
              capabilities: [gpu]    
    devices:
    # this exposes USB deviecs from WSL... which are redirected from windows
    - /dev/ttyUSB0:/dev/ttyUSB0